### ISSUE TITLE
Renaming?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/sphinx-bootstrap-theme-feedstock#2]
It seems we used `-` instead of `_`  ? It seems like their [`pip` install]( https://pypi.python.org/pypi/sphinx-bootstrap-theme#installation ) instructions recommend `sphinx_bootstrap_theme`. Should we be renaming the package @conda-forge/sphinx-bootstrap-theme ?

cc @conda-forge/core

**Comment by ericdill** [comment]
+1 on renaming to be consistent with pip.  Sorry for blindly doing hyphens instead of underscores :disappointed:
