### ISSUE TITLE
Version 0.5.1 not on anaconda.org/conda-forge

### ISSUE THREAD

**Issue by johannesring** [conda-forge/sphinx-bootstrap-theme-feedstock#8]
I want to get `sphinx_bootstrap_theme` built for Python 3.6 and I noticed that the version listed in `meta.yaml`, that is version 0.5.1, is not available on anaconda.org/conda-forge - only version 0.4.9 is available [there](https://anaconda.org/conda-forge/sphinx-bootstrap-theme/files). I re-rendered the package [earlier today](https://github.com/conda-forge/sphinx-bootstrap-theme-feedstock/pull/7) with the latest conda-smithy in the hope that it would make it available for Python 3.6, but it looks like that did not help. Any idea why version 0.5.1 is not available on anaconda.org/conda-forge?

Btw, version 0.5.3 is the latest version available on [pypi](https://pypi.python.org/pypi/sphinx-bootstrap-theme).

**Comment by ericdill** [comment]
@johannesring That's very strange. The CI services indicate that 0.5.1 already exists on anaconda.org/conda-forge, which is clearly does not.

on travis:
```
Distribution /Users/travis/miniconda3/conda-bld/osx-64/sphinx_bootstrap_theme-0.5.1-py36_0.tar.bz2 already exists for conda-forge.
```

on circle-ci:
```
Distribution /feedstock_root/build_artefacts/linux-64/sphinx_bootstrap_theme-0.5.1-py36_0.tar.bz2 already exists for conda-forge.
```

on appveyor:
```
Distribution C:\bld\win-64\sphinx_bootstrap_theme-0.5.1-py36_0.tar.bz2 already exists for conda-forge.
```

Have you seen this before @ocefpaf ?

**Comment by johannesring** [comment]
@scopatz @jakirkham - any ideas on this?

**Comment by scopatz** [comment]
When you rerendered you didn't increase the version number in the meta.yaml. you should bump the version number too.

**Comment by KGHustad** [comment]
With #9, the version number increased, so the files should hopefully appear at https://anaconda.org/conda-forge/sphinx-bootstrap-theme/files soon.

**Comment by KGHustad** [comment]
The CI services all state that the files have been uploaded, but there are still no updates at https://anaconda.org/conda-forge/sphinx-bootstrap-theme/files

[Travis](https://travis-ci.org/conda-forge/sphinx-bootstrap-theme-feedstock/jobs/254880008):
```
Uploaded /Users/travis/miniconda3/conda-bld/osx-64/sphinx_bootstrap_theme-0.5.3-py36_0.tar.bz2
```

[Circle](https://circleci.com/gh/conda-forge/sphinx-bootstrap-theme-feedstock/16):
```
Uploaded /feedstock_root/build_artefacts/linux-64/sphinx_bootstrap_theme-0.5.3-py36_0.tar.bz2
```

[AppVeyor](https://ci.appveyor.com/project/conda-forge/sphinx-bootstrap-theme-feedstock/build/1.0.17/job/mcri0kb5w5wys575):
```
Uploaded C:\bld\win-64\sphinx_bootstrap_theme-0.5.3-py36_0.tar.b
```

**Comment by isuruf** [comment]
See https://github.com/conda-forge/sphinx-bootstrap-theme-feedstock/pull/4

**Comment by ericdill** [comment]
thanks @isuruf . 🤦‍♂️ . It's `sphinx_bootstrap_theme` not `sphinx-bootstrap-theme`... Should we move the one with hyphens to the "broken" label on anaconda.org/conda-forge?

**Comment by jakirkham** [comment]
Also re-rendering the feedstock should update the links to Anaconda from the feedstock Readme to point to the correct location.

**Comment by ericdill** [comment]
I have just moved the sphinx-bootstrap-theme packages (the ones with the hyphens) to "broken" on anaconda.org. Hopefully this will not strike again...

```
$ conda search sphinx_bootstrap_theme
Fetching package metadata ...............
sphinx_bootstrap_theme       0.4.9                    py27_0  conda-forge     
                             0.4.9                    py34_0  conda-forge     
                             0.4.9                    py35_0  conda-forge     
                             0.4.9                    py36_0  conda-forge     
                             0.5.1                    py27_0  conda-forge     
                             0.5.1                    py35_0  conda-forge     
                             0.5.1                    py36_0  conda-forge     
                             0.5.3                    py27_0  conda-forge     
                             0.5.3                    py35_0  conda-forge     
                             0.5.3                    py36_0  conda-forge     
```
